### ISSUE TITLE
Module (Soflomo\Purifier) could not be initialized

### ISSUE THREAD

**Issue by CreativeNative** [Saeven/laminas-mvc-skeleton#1]
I clone the project and run composer install. Than I tried to create the MySQL database for the project with and got this error message. Also in the browser I got this error.
`$ ./vendor/bin/doctrine-module orm:schema-tool:update --force`

This module has got its last update 5 years ago. I am not sure if this should be used anymore.
```
PHP Fatal error:  Uncaught Laminas\ModuleManager\Exception\RuntimeException: Module (Soflomo\Purifier) could not be initialized. in /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/ModuleManager.php:183
Stack trace:
#0 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(155): Laminas\ModuleManager\ModuleManager->loadModuleByName()
#1 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(77): Laminas\ModuleManager\ModuleManager->loadModule()
#2 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\ModuleManager\ModuleManager->onLoadModules()
#3 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#4 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(100): Laminas\EventManager\EventManager->triggerEvent()
#5 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-mvc/src/Application.php(257): Laminas\ModuleManag in /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/ModuleManager.php on line 183

```

**Comment by CreativeNative** [comment]
Found a warning when I installed all composer packages. Not sure if it is related, but maybe it helps.

`Skipped installation of bin bin/purifier-generate-standalone for package saeven/zf3-purifier: file not found in package`

**Comment by CreativeNative** [comment]
When I deleted the module 'Soflomo\Purifier' in the modules.config.php file it complains the same error for the list of modules:
1. Soflomo\Purifier
2. Circlical\LaminasTools
3. Circlical\TailwindForms
4. CirclicalAutoWire
5. CirclicalUser

And than

```
development.local.php.dist
Fatal error: Uncaught Laminas\ModuleManager\Listener\Exception\InvalidArgumentException: Config being merged must be an array, implement the Traversable interface, or be an instance of Laminas\Config\Config. integer given. in /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/Listener/ConfigListener.php:306 Stack trace: #0 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/Listener/ConfigListener.php(340): Laminas\ModuleManager\Listener\ConfigListener->addConfig() #1 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/Listener/ConfigListener.php(121): Laminas\ModuleManager\Listener\ConfigListener->addConfigByPath() #2 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\ModuleManager\Listener\ConfigListener->onMergeConfig() #3 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners() #4 /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/Listener/Confi in /mnt/hgfs/www/skeleton/vendor/laminas/laminas-modulemanager/src/Listener/ConfigListener.php on line 306
```

OK, this "development.local.php.dist" is written in the file development.local.php in plain text, but that's not the problem. I think it's related to PHP8 because I tracked it down until I got this and here my IDE tells me that "Named arguments are only allowed since PHP 8.0". -_-

`Parse error: syntax error, unexpected ':', expecting ')' in /mnt/hgfs/www/skeleton/module/Application/src/Factory/Listener/LayoutListenerFactory.php on line 15`

**Comment by Saeven** [comment]
Yes this example requires PHP8 per its composer.  Why not just install and use the PHP8 built-in web server to test things?  You can easily install them side by each, specially if you are on MacOS with brew.

**Comment by CreativeNative** [comment]
The problem was not PHP8.0 here. My system is now running with PHP8.0 and I get the same error as mentioned above.
